<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c8cb04b9-63d8-4b8b-8792-b29c5e8af7b2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
		my_counter : INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[my_counter := my_counter + my_counter + my_counter + 2;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>